version: "3"
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8000:5173
    working_dir: /src/app
    volumes:
      - type: bind
        source: ./
        target: /src/app
    tty: true